# Generated by Django 2.1.2 on 2018-10-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quest_text',
            new_name='question_text',
        ),
    ]
